# syntax=docker/dockerfile:1.7-labs@sha256:b99fecfe00268a8b556fad7d9c37ee25d716ae08a5d7320e6d51c4dd83246894
# Combines container/builder.dockerfile and container/dist.dockerfile into a
# single multi-stage Dockerfile, then adds a final stage that runs SearXNG
# and the FastAPI gateway (which also serves the dashboard, see
# api/app.py) together via container/start.sh. This one image is what
# gets deployed anywhere - AWS (ECS/EC2 behind an ALB, see README.rst's
# "Deploying on AWS" section) or any other container host.
#
# Build logic for the "builder" and "dist" stages is copied verbatim from
# container/builder.dockerfile and container/dist.dockerfile — do not edit
# those two stages without keeping them in sync with the originals.

# ---------------------------------------------------------------------------
# Stage: builder (== container/builder.dockerfile)
# ---------------------------------------------------------------------------
FROM docker.io/searxng/base:searxng-builder AS builder

COPY ./requirements.txt ./requirements-server.txt ./
COPY ./api/requirements.txt ./api-requirements.txt

ENV UV_NO_MANAGED_PYTHON="true"
ENV UV_NATIVE_TLS="true"

ARG TIMESTAMP_VENV="0"

RUN --mount=type=cache,id=uv,target=/root/.cache/uv set -eux -o pipefail; \
    export SOURCE_DATE_EPOCH="$TIMESTAMP_VENV"; \
    uv venv; \
    uv pip install --requirements ./requirements.txt --requirements ./requirements-server.txt --requirements ./api-requirements.txt; \
    uv cache prune --ci; \
    find ./.venv/lib/ -type f -exec strip --strip-unneeded {} + || true; \
    find ./.venv/lib/ -type d -name "__pycache__" -exec rm -rf {} +; \
    find ./.venv/lib/ -type f -name "*.pyc" -delete; \
    python -m compileall -q -f -j 0 --invalidation-mode=unchecked-hash ./.venv/lib/; \
    find ./.venv/lib/python*/site-packages/*.dist-info/ -type f -name "RECORD" -exec sort -t, -k1,1 -o {} {} \;; \
    find ./.venv/ -exec touch -h --date="@$TIMESTAMP_VENV" {} +

COPY --exclude=./searx/version_frozen.py ./searx/ ./searx/

RUN set -eux -o pipefail; \
    python -m compileall -q -f -j 0 --invalidation-mode=unchecked-hash ./searx/; \
    find ./searx/static/ -type f \
    \( -name "*.html" -o -name "*.css" -o -name "*.js" -o -name "*.svg" \) \
    -exec gzip -9 -k {} + \
    -exec brotli -9 -k {} + \
    -exec gzip --test {}.gz + \
    -exec brotli --test {}.br +

# ---------------------------------------------------------------------------
# Stage: dist (== container/dist.dockerfile)
# ---------------------------------------------------------------------------
FROM docker.io/searxng/base:searxng AS dist

COPY --chown=977:977 --from=builder /usr/local/searxng/.venv/ ./.venv/
COPY --chown=977:977 --from=builder /usr/local/searxng/searx/ ./searx/
COPY --chown=977:977 ./container/ ./
COPY --chown=977:977 ./api/ ./api/
COPY --chown=977:977 ./shared/ ./shared/
COPY --chown=977:977 ./dashboard/ ./dashboard/

ARG CREATED="0001-01-01T00:00:00Z"
ARG VERSION="unknown"
ARG VCS_URL="unknown"
ARG VCS_REVISION="unknown"

# searx/version_frozen.py is normally generated by the project's own build
# tooling (`python -m searx.version freeze`, which shells out to git) before
# handing off to `docker build`. A plain `docker build .` run by a remote
# builder/CI has no such pre-step, and this runtime base image has no `git`
# binary at all — so searx/version.py's git fallback throws an uncaught
# FileNotFoundError and crashes every worker on import. Generate an
# equivalent frozen file here from the VERSION/VCS_* build args instead, so
# it's never missing and never needs git.
RUN set -eux; \
    { \
    echo '# SPDX-License-Identifier: AGPL-3.0-or-later'; \
    echo '# pylint: disable=missing-module-docstring'; \
    echo '# this file is generated automatically by this Dockerfile build'; \
    echo ''; \
    echo "VERSION_STRING = \"$VERSION\""; \
    echo "VERSION_TAG = \"$VERSION\""; \
    echo "DOCKER_TAG = \"$VERSION\""; \
    echo "GIT_URL = \"$VCS_URL\""; \
    echo 'GIT_BRANCH = "unknown"'; \
    } > ./searx/version_frozen.py

LABEL org.opencontainers.image.created="$CREATED" \
    org.opencontainers.image.description="SearXNG is a metasearch engine. Users are neither tracked nor profiled." \
    org.opencontainers.image.documentation="https://docs.searxng.org/admin/installation-docker" \
    org.opencontainers.image.licenses="AGPL-3.0-or-later" \
    org.opencontainers.image.revision="$VCS_REVISION" \
    org.opencontainers.image.source="$VCS_URL" \
    org.opencontainers.image.title="SearXNG" \
    org.opencontainers.image.url="https://searxng.org" \
    org.opencontainers.image.version="$VERSION"

ENV __SEARXNG_VERSION="$VERSION" \
    __SEARXNG_SETTINGS_PATH="$__SEARXNG_CONFIG_PATH/settings.yml" \
    GRANIAN_PROCESS_NAME="searxng" \
    GRANIAN_INTERFACE="wsgi" \
    GRANIAN_HOST="127.0.0.1" \
    GRANIAN_PORT="8081" \
    GRANIAN_WEBSOCKETS="false" \
    GRANIAN_BLOCKING_THREADS="4" \
    GRANIAN_WORKERS_KILL_TIMEOUT="30s" \
    GRANIAN_BLOCKING_THREADS_IDLE_TIMEOUT="5m"

# Bake in a real settings.yml (see container/settings.yml) instead of relying
# on entrypoint.sh's generate-on-first-boot behavior against the template.
COPY --chown=977:977 ./container/settings.yml "$__SEARXNG_CONFIG_PATH/settings.yml"

# "*_PATH" ENVs are defined in base images
VOLUME $__SEARXNG_CONFIG_PATH
VOLUME $__SEARXNG_DATA_PATH

# NOTE: 8080 is no longer EXPOSEd here — the "app" stage below owns the
# externally reachable port and forwards to SearXNG on 127.0.0.1:8081.

ENTRYPOINT ["/usr/local/searxng/entrypoint.sh"]

# ---------------------------------------------------------------------------
# Stage: app (final / default target) — SearXNG + FastAPI gateway + dashboard
# ---------------------------------------------------------------------------
# This is the final image - deploy it anywhere a container runs.
# container/start.sh backgrounds SearXNG on 127.0.0.1:8081 (never reachable
# from outside the container) and foregrounds the FastAPI gateway
# (api/app.py) on the public port, 0.0.0.0:8080 - it's the only thing that
# talks to SearXNG directly, and it also serves the dashboard (mounted in
# api/app.py) from the same process.
#
# No separate auth wrapper sits in front of it (there used to be one, gated
# by a shared AUTH_TOKEN via Caddy - see git history if you need it back for
# some other reason): the gateway has its own route-level auth, and that
# wrapper gated /v1/auth/signup and the dashboard too, which broke
# self-service. See README.rst's "Deploying" section.
FROM dist AS app

# Stays root for the lifetime of the container: start.sh backgrounds
# entrypoint.sh (which itself drops privilege where it can, e.g. chown) and
# foregrounds the FastAPI gateway, so this stage doesn't switch back to the
# non-root searxng user the base image normally runs as.
USER root

COPY ./container/start.sh /usr/local/searxng/start.sh
RUN chmod +x /usr/local/searxng/start.sh

EXPOSE 8080

ENTRYPOINT ["/usr/local/searxng/start.sh"]
